base/Dockerfile

Adding a comment about a setting that is sterile in our base image.

Add comment about enabling prompt color

---

swan/Dockerfile

Contains fix to show extension that switches to old UI.

swan: Upgrade SwanContents to v2.1.1

---

.gitlab-ci.yml

To build each image in GitLab runners whenever there is a new version to be deployed

Add CI/CD pipeline for GitLab

---

swan/Dockerfile

Has a fix for nbextensions configurator.

swan: Update SwanContents to v2.1.3

---

swan/Dockerfile

Added to allow tex outputs to be converted to png.

swan: Add tex dvipng package

---

swan-accpy/Dockerfile

This PR updates the current swancustomenvironments version of and separates the splits its installation layer from its configuration

swan-accpy: update swancustomenvironments version & change on Dockerfile

---

.github/workflows/update-images.yaml
.github/workflows/update-packages.yaml

When one of the python packages created by the SWAN team has their version bumped, a pull request will be automatically created in this repository, to bump the version of the package in the SWAN image it belongs to.

ci: Automatically create PR for new package versions

---

swan-cern/Dockerfile

Contains fix for SwanContents and readme.md files

[swan-cern] Update swan base image to v0.0.17

---

swan-accpy/Dockerfile

swan-cern: v0.0.25 to v0.0.26
swancustomenvironments: v0.0.5 to v0.0.6

swan-accpy: update swan-cern image and swancustomenvironments

---

swan-accpy/Dockerfile

swan-cern: v0.0.25 to v0.0.26
swancustomenvironments: from 0.0.5 to 0.0.7

swan-accpy: Update swan-cern image and swancustomenvironments versions

---

swan-accpy/Dockerfile

swan-accpy: Update swancustomenvs

---

swan-accpy/Dockerfile

swan-accpy: Update swancustomenvironments

---

swan-accpy/Dockerfile

swancustomenvironments: from 0.0.12 to 0.0.15

swan-accpy: Update swancustomenvironments version to 0.0.15

---

swan-accpy/Dockerfile

swancustomenvironments: from 0.0.15 to 0.0.16

swan-accpy: Update swancustomenvironments version to 0.0.16

---

swan-accpy/Dockerfile

swancustomenvironments: from 0.0.16 to 0.0.17

swan-accpy: Update swancustomenvironments version to 0.0.17

---

swan-cern/scripts/before-notebook.d/10_spark.sh

NXCALS team requested this bundle also for customenvs. So we extract the extraJavaOptions from the bundles on CVMFS and put it in the right path in order to SparkConnector find it.

swan-cern: Add NXCALS TESTBED bundle to customenvs

---

swan-accpy/Dockerfile

swancustomenvironments: from 0.0.17 to 0.0.18

swan-accpy: Update swancustomenvironments version to 0.0.18

---

swan-accpy/Dockerfile

swancustomenvironments: from 0.0.18 to 0.0.20

swan-accpy: Update swancustomenvironments version to 0.0.20

---

swan-accpy/Dockerfile

swancustomenvironments: from 0.0.20 to 0.0.21

swan-accpy: Update swancustomenvironments version to 0.0.21

---

swan-accpy/Dockerfile

Update swan-cern image to v0.0.30
Update swancustomenvironments version to 0.0.22

Update swan-cern and swancustomenvironments versions

---

.github/workflows/cascade-image-update.yaml

Replace the versions of the parent images in the correct place, to update the VERSION_PARENT variable

Target correct variable to update parent version

---

swan-accpy/Dockerfile

swancustomenvironments: from 0.0.22 to 0.0.23

swan-accpy: Update swancustomenvironments version to 0.0.23

---

swan-accpy/Dockerfile

swancustomenvironments: from 0.0.23 to 0.0.24

swan-accpy: Update swancustomenvironments version to 0.0.24

---

swan-accpy/Dockerfile

swancustomenvironments: from 0.0.24 to 0.0.25

swan-accpy: Update swancustomenvironments version to 0.0.25

---

swan-accpy/Dockerfile

swancustomenvironments: from 0.0.26 to 0.0.27

swan-accpy: Update swancustomenvironments version to 0.0.27

---

swan-accpy/Dockerfile
swan-cern/scripts/before-notebook.d/10_spark.sh
swan/Dockerfile
swan/scripts/before-notebook.d/02_environment.sh

This PR includes a new swan-accpy instance (base on top of swan-cern) and all the necessary modifications on previous approaches, in order to fill all the requirements imposed by the Swan-on-TN project.

Swan-on-TN
