base/Dockerfile

This setting disables the creation of the home directory for new users, which is enabled by default. It is needed, so that the start.sh script is able to create the directory and copy the files from jovyan to the new user home.

base: Disable the creation of the home directory for new users

---

base/start.sh

This instruction was added to the file by mistake, by me. The jovyan home is changed to the NB_USER home but a symlink is created for /home/jovyan still.

base: Remove unecessary instruction from start.sh

---

base/Dockerfile

The version of jupyter_core is the most recent one at this time (5.5.0). However, the version of mamba is the second most recent (1.5.3), as the most recent one (1.5.4) is preventing the image from compiling due to issues with the `mamba clean` command.

base: Force versions of mamba and jupyter_core packages

---

swan/Dockerfile

Contains fix for working directories of notebooks and a new lab extension to switch to the old UI.

Install SwanContents v2.1.0

---

swan/Dockerfile

Otherwise COPY complains:
When using COPY with more than one source file, the destination must be a directory and end with a /

Add slash at destination directory

---

base/Dockerfile
base/patches/log_patch.diff

While we wait for fix to be merged in (presumably) JupyterHub 4.0.3

Add patch to prevent printing of tokens by Jupyter server

---

swan/Dockerfile
swan/patches/jupyter_server_proxy.diff

To prevent double formatting of environment variables.
See PR upstream:
https://github.com/jupyterhub/jupyter-server-proxy/pull/437

Add patch to jupyter-server-proxy

---

base/Dockerfile

I'm pushing this, will address other issues later.

base: remove warnings when creating/switching user

---

swan/Dockerfile

Install glibc-langpack-en package, as the R configuration requires the en_US.UTF-8 enconding.

swan: Add en langpacks required by R configuration

---

swan-cern/Dockerfile
swan/Dockerfile

It is not clear that the Cloudera dependencies are still needed, removing their installation now, will readd if needed.
For Oracle, libaio is in the LCG releases, so it should not be needed either.

swan-cern: Remove Cloudera and Oracle dependencies

---

swan/Dockerfile

The packages that were being installed through tlmgr (TexLive package manager) are already installed when TexLive is installed through DNF. Therefore, the instruction to install them through tlmgr is not necessary.

swan: Remove texlive packages installation instruction

---

swan-cern/Dockerfile

Has fix to automatically enable the extension.

swan-cern: Upgrade SwanPortAllocator to v1.0.2

---

swan-cern/Dockerfile

This is the first JupyterLab4-compatible version.

swan-cern: Upgrade SparkMonitor to 3.0.1

---

swan-cern/Dockerfile

Fixes new naming of host_allowlist.

swan-cern: Upgrade SwanDask to v0.0.5

---

swan/Dockerfile

Install required texlive packages through dnf, to convert notebooks into different formats using texlive, since they are not installed as dependencies of texlive.

swan: Install required packages for texlive

---

swan/Dockerfile

Before this commit, the ipykernel and dependencies were taken from the LCG release selected by the user. This has caused an incompatibility problem when upgrading Jupyter packages to be included in the new Alma9 user image.
Here we expose ipykernel and some of its dependencies to the user environment in notebooks, to enforce an ipykernel version that comes from (and is compatible with) the image, instead of from the LCG release. This ensures we run the Python kernels with the same package versions as the Jupyter server.
The reason to only symlink ipykernel and three of its dependencies is that, when installing an updated ipykernel on top of the current Bleeding edge software stack, only those packages needed to be updated -- the rest can be safely taken from the LCG release, at least with …

swan: Enforce an ipykernel version for compatibility reasons

---

swan-cern/Dockerfile

It uses the alma9-based user image for the Dask workers.

swan-cern: Upgrade SwanDaskCluster to v3.0.0

---

swan/Dockerfile

This PR contains commits that disable python extensions which are not fully operational yet and require further investigation.

Disable python extensions that are not 100% operational

---

swan-cern/scripts/before-notebook.d/10_spark.sh
swan/scripts/before-notebook.d/02_environment.sh

Use the correct name of the sparkconnector extension, to be disabled if spark is not being used. In addition, when spark is being used, add sparkconnector setting to ipython kernel configuration file

swan-cern: Change extension and update ipython kernel configuration file

---

swan-cern/scripts/before-notebook.d/10_spark.sh

We need to prepend the activation of the spark monitor to the configuration file as well, so that the extension is loaded before swankernelenv, which removes the extensions directory from sys.path

swan-cern: Prepend activation of sparkmonitor to ipython config file

---

swan/scripts/before-notebook.d/02_environment.sh

This is done to prevent the Jupyter server from creating runtime files in the EOS home dir, both for performance reasons and not to make those files persistent.
This was done already in the systemuser image:
https://github.com/swan-cern/systemuser-image/blob/master/systemuser.sh#L70

swan: Define JUPYTER_RUNTIME_DIR to point to local scratch home

---

swan/scripts/before-notebook.d/02_environment.sh

Not to pollute EOS HOME dir with log files from npm and for performance sake.

swan: Place npm cache in local scratch directory

---

swan/scripts/before-notebook.d/02_environment.sh

To prevent it from creating a .local directory on EOS.

swan: Add JUPYTER_DATA_DIR to Jupyter server environment

---

swan/Dockerfile

This extension is implemented on the swan image to allow the users to keep track of their files, code, and its changes

Add jupyterlab-git extension

---

swan-cern/Dockerfile

Install spark extensions for the SWAN classic UI, in order to allow users to use spark through such UI in the Alma9 image.

swan-cern: Install spark extensions

---

swan-cern/Dockerfile
swan-cern/scripts/before-notebook.d/11_htcondor.sh

voms-proxy-init java client
Links to /cvmfs/grid.cern.ch in the condor context (if the cvmfs is mounted)

Adds voms-proxy-init and links to cvmfs grid voms

---

swan-cern/scripts/before-notebook.d/11_htcondor.sh

So that users can create their proxies to external data sources or the grid more easily. Using a voms-proxy-init from CVMFS also prevents the installation of the tool in the image, which we want to keep thin.
To be replaced when the corresponding Alma9 voms-proxy-init is available on /cvmfs/grid.cern.ch.

swan-cern: Create symlink to voms-proxy-init on grid.cern.ch

---

.gitlab-ci.yml

Fix issue that was being caused by using the full name of the image instead of the version tag only.

ci: use image version as BUILD_TAG for SWAN images

---

swan-cern/scripts/before-notebook.d/10_spark.sh
swan/scripts/before-notebook.d/02_environment.sh

This fixes an issue with SWAN that was preventing users to use matplotlib plots in an interactive mode, by enabling the jupyter-matplotlib and widgets extensions.

swan: Fix matplotlib plots not being interactive

---

swan-cern/scripts/before-notebook.d/11_htcondor.sh
swan-cern/scripts/before-notebook.d/12_proxy_certs.sh

There are SWAN users that require the initialization of VOMS independently of dask. Therefore, those instructions were separated and now VOMS initializes everytime a user starts their session.

swan-cern: Add support for VOMS regardless of the usage of dask

---

swan/scripts/others/userconfig.sh

The user can select to automatically prepend the local python packages directory to the PYTHONPATH variable, thus being able to import any package installed on their CERNBox in their SWAN notebooks.

swan: Prepend local python packages directory to PYTHONPATH

---

swan-accpy/Dockerfile
swan/scripts/before-notebook.d/02_environment.sh
swan/scripts/others/userconfig.sh

A new image built on top of `swan-cern` was built in order to attend the demand of Beams Department to have their `acc-py` framework distributed across SWAN for creating custom environments. For supporting this purpose, a new AccPy image was developed with:
- 3 versions of acc-py (2020.11, 2021.12, 2023.06)
- java11-openjdk
- SwanCustomEnvironments configuration (temporary)
Apart from that, a small prevention for avoiding the LCG configuration made in `02_environment.sh`, in case a custom environment is launched instead of an usual LCG session.

New image for custom environments

---

swan-cern/scripts/before-notebook.d/12_proxy_certs.sh

This symlink is added per request of a user, that was being unable to find the location of the binary file for the command, to improve the user experience when using voms.

swan-cern: Add symlink for voms-proxy-info command

---

.github/workflows/update-images.yaml

All of the images present in this repo always start with "jupyter" (e.g. jupyter/swan-cern). Make sure this is reflected in the CI when passing the image name.

ci: Prepend the base name of the jupyter image

---

swan-cern/Dockerfile

With the addition of cronie, the CVMFS prefetcher container of the CVMFS-CSI chart can use the same image as the user container. This is useful because we make sure that the source and python commands executed by the prefetcher run without errors in the same environment as the user (image, LCG views from CVMFS).
Note: cronie just adds a few hundreds of KB to the image.

swan-cern: Install cronie

---

swan-cern/Dockerfile

This reverts commit d611d2a0398cf5b346d8a3b6d8517c88c5b18763.
The prefetcher container in CVMFS-CSI will have its own image. This change was motivated by the fact that swan-cern runs by default with user jovyan, but we need it to run as root to executed crond.

Revert "swan-cern: Install cronie"

---

prefetcher/Dockerfile

This image was introduced to run the warmup jobs for the LCG releases, as the default swan-cern image runs as the jovyan user while the image needs to run as root because of cronie

prefetcher: Add prefetcher image for CVMFS

---

base/Dockerfile

Because of https://github.com/jupyterhub/jupyterhub/issues/4629.

Update hub version and alma9 base image tag

---

swan-cern/Dockerfile

Contains a fix for SwanShare and SwanContents.

[swan-cern] Update swan image to v0.0.16

---

swan/scripts/before-notebook.d/02_environment.sh

The script suffered from:
- Unmatched end of conditional block
- Repeated code blocks
- Need for change of ownership of LOCAL_HOME (custom envs case)
In addition, the emission of a custom metric for the kernel configuration time was removed when custom envs are selected, since kernels are not configured in this script in the latter case.

[swan] Fix 02_environment.sh script

---

swan/scripts/before-notebook.d/02_environment.sh

Since it is necessary for both LCG and Custom Environments. In the latter, it loads the environment and cds into the environment folder when starting a terminal.

[swan] Move source of .bash_profile out of conditional block

---

swan-accpy/Dockerfile

Has fix to see just one Python kernel.

[swan-accpy] Update SwanCustomEnvs to v0.0.5

---

swan-cern/Dockerfile

Contains new version of jupyter-resource-usage.

[swan-cern] Update to swan v0.0.18

---

swan/Dockerfile

This is done to avoid keeping `/opt/conda/pkgs` alive, in order to keep mamba warning messages away from the user when creating mamba custom environments

swan: Cleaning up the mamba cache

---

swan-cern/scripts/before-notebook.d/10_spark.sh

This is made in order to prevent errors when launching customenv sessions (they don't create this folder, since `userconfig.sh` is not executed)

swan-cern: Bypass `nbconfig` folder not found

---

swan-accpy/Dockerfile

UV is useful for replacing pip when installing requirements on accpy custom environments

swan-accpy: Install `uv` package manager

---

swan/Dockerfile

Includes cyrus-sasl-gssapi to support a Kafka use case from SWAN.
More information:
https://its.cern.ch/jira/browse/SPI-2688

[swan] Update HEP_OSlibs to v9.2.3-1

---

base/Dockerfile
base/start.sh
swan/config/kernel.json

Start the singleuser server without taking into account the packages the user has installed in their EOS, as they may conflict with the setup of the server due to older versions, etc.

Run jupyterhub singleuser isolated

---

.github/workflows/cascade-image-update.yaml

Only activate the workflow when specific tags are pushed to the repo, related to the user images

ci: Specify which tags trigger the workflow

---

.github/workflows/cascade-image-update.yaml

Checkout the main branch when running the CI to update the images versions on cascade

ci: Checkout main branch always

---

swan/scripts/others/userconfig.sh

Set this variable with the path of the Python packages on the user EOS so that the user does not need to add the --user flag to the pip command every time they want to install a package in their CERNBox

swan: Set PIP_TARGET env variable

---

swan/scripts/others/userconfig.sh

This reverts commit 6cd7b28f087ec8e256017162da74b5e1bd99c5b2.
When a user uses --user flag, pip errors out as we already force the usage of the --target flag with the PIP_TARGET variable. Moreover, when a session is started with custom environments, the packages should not be installed by default in the user CERNBox (i.e. in the site-packages in their CERNBox).

Revert "swan: Set PIP_TARGET env variable"

---

swan/python/jupyter_server_config.py

Force the PDF exporter command to use the temporary user home, to prevent it touching the user EOS and with that reduce the time it takes for a notebook to be exported to PDF

swan: Use custom PDFExporter command to reduce PDF export time

---

swan/scripts/before-notebook.d/02_environment.sh

The git command is supposed to touch the local user home in the container instead of EOS, when adding the git configuration file

swan: Force the git command to run locally

---

swan/scripts/others/userconfig.sh

PYTHONNOUSERSITE is set to 1 in the base image to prevent the Jupyter server process, notebook processes and terminal processes from inspecting the user site packages directory by default.
However, if PYTHONNOUSERSITE is set to 1, editable packages are ignored by Python (see SWAN-410 for more details). Therefore, if the user selects to work with packages installed on CERNBox (editable or not), we unset PYTHONNOUSERSITE to prevent breaking the editable package search mechanism.

swan: [SWAN-410] Allow editable packages to be found by Python
